from __future__ import annotations

from ..schemas.medicine import Medicine


DEFAULT_MEDICINES = [
    {
        "id": "aspirin-enteric",
        "slot": "A01",
        "name": "阿司匹林肠溶片",
        "category": "慢病常用",
        "tags": ["心脑血管", "长期管理"],
        "contraindications": ["胃肠道出血风险", "阿司匹林过敏禁用"],
        "stock": 36,
        "unit": "盒",
        "expire_date": "2027-11-30",
        "image_hint": "蓝白药盒",
        "is_otc": False,
        "is_emergency": False,
        "safety_note": "取药前核对既往过敏史、出血风险和用药医嘱。",
    },
    {
        "id": "nifedipine-controlled",
        "slot": "A02",
        "name": "硝苯地平控释片",
        "category": "慢病常用",
        "tags": ["血压管理", "控释片"],
        "contraindications": ["低血压风险", "请勿掰开或嚼碎"],
        "stock": 24,
        "unit": "盒",
        "expire_date": "2027-09-18",
        "image_hint": "红白药盒",
        "is_otc": False,
        "is_emergency": False,
        "safety_note": "取药前确认血压监测情况和既往用药记录。",
    },
    {
        "id": "ibuprofen-sustained",
        "slot": "B01",
        "name": "布洛芬缓释胶囊",
        "category": "感冒发热",
        "tags": ["发热", "疼痛"],
        "contraindications": ["消化道溃疡慎用", "孕晚期禁用"],
        "stock": 28,
        "unit": "盒",
        "expire_date": "2027-06-15",
        "image_hint": "橙白药盒",
        "is_otc": True,
        "is_emergency": True,
        "safety_note": "避免与同类退热镇痛药重复使用，注意用量间隔。",
    },
    {
        "id": "lianhua-qingwen",
        "slot": "B02",
        "name": "连花清瘟胶囊",
        "category": "感冒发热",
        "tags": ["感冒", "咽痛"],
        "contraindications": ["过敏体质慎用", "儿童需监护确认"],
        "stock": 18,
        "unit": "盒",
        "expire_date": "2026-12-20",
        "image_hint": "绿色药盒",
        "is_otc": True,
        "is_emergency": False,
        "safety_note": "取药前核对症状持续时间和合并用药情况。",
    },
    {
        "id": "montmorillonite-powder",
        "slot": "C01",
        "name": "蒙脱石散",
        "category": "肠胃",
        "tags": ["腹泻", "肠胃"],
        "contraindications": ["便秘慎用", "需与其他药物错开服用"],
        "stock": 20,
        "unit": "袋",
        "expire_date": "2027-04-10",
        "image_hint": "黄色药袋",
        "is_otc": True,
        "is_emergency": True,
        "safety_note": "注意补液观察，严重脱水或持续高热需及时转诊。",
    },
    {
        "id": "loratadine-tablet",
        "slot": "D01",
        "name": "氯雷他定片",
        "category": "过敏",
        "tags": ["过敏", "鼻炎"],
        "contraindications": ["严重肝功能异常慎用", "过敏禁用"],
        "stock": 16,
        "unit": "盒",
        "expire_date": "2027-08-05",
        "image_hint": "浅蓝药盒",
        "is_otc": True,
        "is_emergency": False,
        "safety_note": "取药前确认过敏表现，呼吸困难等严重情况需立即转诊。",
    },
    {
        "id": "iodophor-swab",
        "slot": "E01",
        "name": "碘伏棉签",
        "category": "外伤消毒",
        "tags": ["外伤", "消毒"],
        "contraindications": ["碘过敏禁用", "深部伤口需专业处理"],
        "stock": 120,
        "unit": "包",
        "expire_date": "2028-01-12",
        "image_hint": "消毒棉签包",
        "is_otc": True,
        "is_emergency": True,
        "safety_note": "用于皮肤表面消毒，污染严重或出血不止需转诊。",
    },
    {
        "id": "adhesive-bandage",
        "slot": "E02",
        "name": "创可贴",
        "category": "外伤消毒",
        "tags": ["外伤", "包扎"],
        "contraindications": ["感染伤口慎用", "皮肤胶布过敏慎用"],
        "stock": 150,
        "unit": "盒",
        "expire_date": "2028-03-01",
        "image_hint": "创可贴盒",
        "is_otc": True,
        "is_emergency": True,
        "safety_note": "仅用于浅表小伤口，红肿渗液或疼痛加重需进一步处理。",
    },
]


class MedicineRepository:
    def list_all(self) -> list[Medicine]:
        return [Medicine(**item) for item in DEFAULT_MEDICINES]

    def get_by_id(self, medicine_id: str) -> Medicine | None:
        return next((medicine for medicine in self.list_all() if medicine.id == medicine_id), None)
